spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/category_bot
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
bot:
    name: test_intern_pandev_bot
    token: 7664107256:AAFkB3sG8AoGJxKcsElp6rLuj3bbn7x-9I4